/**
 * FinBest AI - Additional Knowledge Base Seed
 * Adds ESG, behavioral finance, IDX market structure, stock analysis docs.
 */
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

function buildContent(lines: string[]): string {
  return lines.join('\n')
}

const additionalDocs = [
  // ============ ESG ============
  {
    title: 'Panduan Investasi ESG: Environmental, Social, Governance',
    category: 'education',
    source: 'FinBest AI Knowledge Base - MSCI ESG Framework',
    summary:
      'ESG adalah kerangka evaluasi investasi berdasarkan Environmental (lingkungan), Social (sosial), dan Governance (tata kelola). Skor ESG MSCI membantu investor menyelaraskan portofolio dengan nilai pribadi.',
    content: buildContent([
      'INVESTASI ESG (ENVIRONMENTAL, SOCIAL, GOVERNANCE):',
      '',
      'ESG adalah kerangka evaluasi investasi yang menilai perusahaan dari tiga dimensi non-finansial yang berdampak pada keberlanjutan jangka panjang.',
      '',
      '1. ENVIRONMENTAL (LINGKUNGAN)',
      'Faktor yang dinilai: emisi karbon, efisiensi energi, manajemen air dan limbah, praktik pertanian berkelanjutan, kepatuhan regulasi lingkungan.',
      'Contoh perusahaan dengan skor E tinggi: sektor renewable energy, perusahaan dengan komitmen net-zero emissions.',
      '',
      '2. SOCIAL (SOSIAL)',
      'Faktor: kesehatan dan keselamatan karyawan, praktik ketenagakerjaan, hubungan komunitas, keberagaman dan inklusi, rantai pasokan etis.',
      '',
      '3. GOVERNANCE (TATA KELOLA)',
      'Faktor: struktur dewan komisaris, kepemilikan saham manajemen, praktik akuntansi, kepatuhan hukum, perlindungan pemegang saham minoritas.',
      '',
      'SKOR ESG MSCI: AAA-AA (Leader), A-BB (Average), BB-C (Laggard).',
      '',
      'STRATEGI INVESTASI ESG:',
      '1. Negative Screening: hindari sektor kontroversial (tembakau, judi, senjata)',
      '2. Positive Screening: pilih perusahaan dengan skor ESG terbaik di sektor',
      '3. Thematic Investing: investasi pada tema ESG (clean energy, gender diversity)',
      '4. Impact Investing: investasi dengan tujuan dampak terukur (CO2 offset)',
      '',
      'DAMPAK TERUKUR: carbon offset, social impact (SDG), board diversity.',
      'Pertumbuhan investasi ESG di Indonesia mencapai 89% per tahun (2024).',
    ]),
  },
  {
    title: 'MSCI ESG Ratings: Metodologi dan Penerapan untuk Investor Indonesia',
    category: 'financials',
    source: 'MSCI ESG Research LLC - 2024',
    summary:
      'MSCI ESG Ratings menilai perusahaan dari AAA hingga CCC berdasarkan 10 tema (climate change, natural capital, pollution, environmental opportunity, human capital, product liability, stakeholder opposition, social opportunity, corporate governance, corporate behavior).',
    content: buildContent([
      'METODOLOGI MSCI ESG RATINGS:',
      '',
      'SKALA RATING:',
      '- AAA, AA: Leader - memimpin industri dalam mengelola risiko ESG',
      '- A, BBB: Average - risiko ESG terkelola dengan baik',
      '- BB, B: Laggard - paparan risiko ESG tinggi, pengelolaan lemah',
      '- CCC: Tertinggal - risiko ESG tidak terkelola',
      '',
      '10 TEMA PENILAIAN:',
      '',
      'LINGKUNGAN:',
      '1. Climate Change: emisi karbon, risiko fisik iklim, peluang transisi rendah karbon',
      '2. Natural Capital: kebutuhan air, keanekaragaman hayati, penggunaan lahan',
      '3. Pollution & Waste: emisi toxic, limbah elektronik, kemasan plastik',
      '4. Environmental Opportunity: teknologi hijau, energi terbarukan, bangunan hijau',
      '',
      'SOSIAL:',
      '5. Human Capital: kesehatan karyawan, keberagaman, pelatihan, hubungan industrial',
      '6. Product Liability: keamanan produk, privasi data, pemasaran bertanggung jawab',
      '7. Stakeholder Opposition: kontroversi komunitas, hak masyarakat adat',
      '8. Social Opportunity: akses keuangan, nutrisi, kesehatan, pendidikan',
      '',
      'TATA KELOLA:',
      '9. Corporate Governance: struktur dewan, kompensasi eksekutif, kepemilikan',
      '10. Corporate Behavior: etika bisnis, anti-korupsi, transparansi pajak',
      '',
      'PENERAPAN UNTUK INVESTOR INDONESIA:',
      '- Saham BEI dengan skor ESG relatif tinggi: TLKM (governance), BBCA (governance), UNVR (social)',
      '- Saham dengan risiko ESG: tambang batubara (PTBA, ITMG, ADRO) - risiko climate change tinggi',
      '- Reksa dana ESG: BNP Paribas Sustainable Equity, Schroders ESG',
      '',
      'CATATAN: Skor ESG bukan jaminan return. Studi menunjukkan perusahaan dengan ESG tinggi cenderung lebih resilien dalam krisis.',
    ]),
  },

  // ============ BEHAVIORAL FINANCE ============
  {
    title: 'Deteksi Bias Kognitif: FOMO, Herding, dan Overconfidence',
    category: 'education',
    source: 'FinBest AI - Bias Detection Engine',
    summary:
      'Tiga bias kognitif paling merugikan investor Gen Z Indonesia: FOMO (membeli karena takut ketinggalan), Herding (mengikuti massa), Overconfidence (terlalu percaya diri). Pelajari gejala dan cara mengatasinya.',
    content: buildContent([
      'TIGA BIAS KOGNITIF UTAMA INVESTOR INDONESIA:',
      '',
      '1. FOMO (FEAR OF MISSING OUT)',
      'Definisi: Kecemasan tertinggal tren profit, mendorong beli aset yang sudah naik tinggi.',
      '',
      'GEJALA DETEKSI:',
      '- Membeli aset yang naik >15% dalam 5 hari perdagangan',
      '- Frekuensi cek harga >5x per hari',
      '- Beli tanpa analisis fundamental, hanya karena "naik terus"',
      '- Mendengar teman/sosial media dapat profit, langsung ikut beli',
      '- Menggunakan dana pinjaman (pinjol) untuk investasi',
      '',
      'DAMPAK: Investor FOMO rata-rata beli di puncak, rugi saat koreksi.',
      '',
      'PENANGANAN:',
      '- Cooling-off 30 menit sebelum konfirmasi beli',
      '- Tanyakan: "Apakah saya beli karena FOMO atau analisis?"',
      '- Set aturan: tidak beli aset yang naik >10% dalam 1 minggu',
      '- DCA (dollar cost averaging) lebih baik daripada lump sum saat tren naik',
      '',
      '2. HERDING (IKUT-IKUTAN)',
      'Definisi: Mengikuti keputusan investasi massa atau influencer tanpa analisis mandiri.',
      '',
      'GEJALA DETEKSI:',
      '- Beli saham karena trending di Twitter/X atau TikTok',
      '- Ikut forum/rekomendasi grup WhatsApp tanpa due diligence',
      '- Jual saat semua orang jual (panik massal)',
      '- Beli saham "gorengan" yang direkomendasikan grup',
      '',
      'DAMPAK: Herding menciptakan bubble dan crash. Investor herding cenderung kalah dari indeks.',
      '',
      'PENANGANAN:',
      '- Buat thesis investasi tertulis sebelum beli',
      '- Batasi pengaruh social media pada keputusan investasi',
      '- Bandingkan rekomendasi dengan data fundamental (PER, PBV, ROE)',
      '- Konsultasi dengan advisor independen, bukan influencer',
      '',
      '3. OVERCONFIDENCE (TERLALU PERCAYA DIRI)',
      'Definisi: Investor merasa bisa "mengalahkan pasar" padahal statistik 95% trader aktif kalah dari indeks.',
      '',
      'GEJALA DETEKSI:',
      '- Trading frekuensi tinggi (>20 transaksi/bulan)',
      '- Konsisten mengklaim profit besar tanpa dokumentasi',
      '- Percaya bisa "timing market" (beli di bawah, jual di atas)',
      '- Mengabaikan diversifikasi, konsentrasi pada 1-2 saham',
      '- Tidak mau cut loss karena "pasti akan naik lagi"',
      '',
      'DAMPAK: Overconfidence menyebabkan overtrading, biaya transaksi tinggi, return di bawah indeks.',
      '',
      'PENANGANAN:',
      '- Audit performa: bandingkan return Anda dengan IHSG',
      '- Batasi frekuensi transaksi (maksimal 4/bulan)',
      '- Wajibkan rencana exit sebelum entry (stop-loss, target)',
      '- Diversifikasi: minimal 5 saham di 3 sektor berbeda',
      '',
      'STATISTIK PENELITIAN:',
      '- 55,38% investor Gen Z di Indonesia terdorong FOMO (Lazuardi, 2025)',
      '- Investor herding mengalami return 2-4% di bawah indeks (Sugianto et al., 2024)',
      '- 95% day trader aktif kehilangan uang dalam jangka panjang',
      '',
      'FinBest AI menggunakan Bias Detection Engine berbasis NLP untuk mendeteksi sinyal-sinyal bias ini dari pola transaksi dan konteks pertanyaan pengguna.',
    ]),
  },
  {
    title: 'Behavioral Finance: Loss Aversion, Anchoring, dan Confirmation Bias',
    category: 'education',
    source: 'FinBest AI Knowledge Base',
    summary:
      'Loss aversion (rasa rugi 2x lebih sakit dari senang untung), anchoring (terpaku harga beli awal), confirmation bias (cari info yang mendukung keputusan). Ketahui gejala dan strategi mengatasinya.',
    content: buildContent([
      'BIAS KOGNITIF TAMBAHAN DALAM INVESTASI:',
      '',
      '1. LOSS AVERSION',
      'Konsep: Daniel Kahneman & Amos Tversky (1979) - Prospect Theory.',
      'Rasa sakit kerugian ~2x lebih kuat dari kepuasan keuntungan setara.',
      '',
      'GEJALA: menahan saham rugi terlalu lama, menjual saham untung terlalu cepat, tidak mau realisasi rugi meski fundamental berubah.',
      '',
      'STRATEGI: set stop-loss disiplin (-10% atau -15%), evaluasi fundamental bukan harga beli, rebalance berkala.',
      '',
      '2. ANCHORING',
      'Definisi: Terpaku pada angka referensi tertentu (biasanya harga beli atau harga tertinggi historis).',
      '',
      'GEJALA: "Saham ini dulu Rp 10.000, sekarang Rp 5.000, pasti balik", menolak jual meski fundamental memburuk.',
      '',
      'STRATEGI: evaluasi berdasarkan prospek masa depan bukan harga beli, tanyakan "Jika saya tidak punya saham ini, apakah saya akan beli?".',
      '',
      '3. CONFIRMATION BIAS',
      'Definisi: Mencari dan mengutamakan informasi yang mendukung keputusan yang sudah dibuat.',
      '',
      'GEJALA: hanya baca riset yang mendukung saham yang sudah dimiliki, mengabaikan berita negatif.',
      '',
      'STRATEGI: sengaja cari "bear case" untuk setiap saham, baca riset dari multiple sumber, assign devil advocate.',
      '',
      '4. RECENCY BIAS',
      'Definisi: Memberi bobot berlebih pada event baru, mengabaikan data jangka panjang.',
      '',
      'GEJALA: panik setelah koreksi 1 minggu, euforia setelah rally 1 bulan.',
      '',
      'STRATEGI: lihat grafik 10 tahun bukan 1 bulan, ingat koreksi 10% terjadi rata-rata 1-2x per tahun (normal).',
      '',
      '5. SUNK COST FALLACY',
      'Definisi: Melanjutkan investasi karena sudah "terlanjur" rugi/belanja, meski tidak rasional.',
      '',
      'GEJALA: "Saya sudah rugi Rp 5 juta, harus ditahan sampai balik", menambah posisi saham rugi tanpa analisis.',
      '',
      'STRATEGI: evaluasi setiap keputusan secara independen, sunk cost bukan alasan untuk tetap investasi.',
      '',
      'FinBest AI membantu pengguna mengenali bias ini melalui pre-trade reflection questions, behavioral audit trail bulanan, dan edukasi terpersonalisasi berdasarkan pola transaksi.',
    ]),
  },

  // ============ IDX MARKET STRUCTURE ============
  {
    title: 'Struktur Pasar Modal Indonesia: BEI, KSEI, KPEI',
    category: 'regulations',
    source: 'Bursa Efek Indonesia - 2024',
    summary:
      'Pasar modal Indonesia diatur oleh OJK, dengan BEI sebagai bursa, KSEI sebagai kustodian, KPEI sebagai lembaga kliring. IDX Composite (IHSG) adalah indeks utama. Investor ritel mencapai 20,13 juta SID per Desember 2025.',
    content: buildContent([
      'STRUKTUR PASAR MODAL INDONESIA:',
      '',
      '1. OTORITAS JASA KEUANGAN (OJK)',
      '- Regulator pasar modal, perbankan, dan industri keuangan non-bank',
      '- Berwenang mengatur, mengawasi, dan memberikan sanksi',
      '- Menerbitkan POJK (Peraturan OJK) dan SOJK (Surat Edaran OJK)',
      '',
      '2. BURSA EFEK INDONESIA (BEI/IDX)',
      '- Bursa saham utama Indonesia (gabungan BES dan SSX sejak 2007)',
      '- Menyediakan tempat perdagangan saham, obligasi, reksa dana, derivatif',
      '- Indeks utama: IDX Composite (IHSG), LQ45, IDX30, IDX80, JII',
      '- Jam perdagangan: Senin-Jumat, 09:00-15:00 WIB (sesi reguler)',
      '',
      '3. KUSTODIAN SENTRAL EFEK INDONESIA (KSEI)',
      '- Lembaga penyimpanan dan penyelesaian transaksi efek',
      '- Mengelola Sub-Rekening Efek Nasabah (SID)',
      '- Per Desember 2025: 20,13 juta SID investor ritel (99,78% lokal)',
      '',
      '4. KLIRING PENJAMINAN EFEK INDONESIA (KPEI)',
      '- Lembaga kliring dan penjaminan penyelesaian transaksi',
      '- Menjamin settlement T+2 (transaction day + 2 hari bursa)',
      '',
      'INDEKS UTAMA BEI:',
      '- IDX Composite (IHSG): indeks seluruh saham listed',
      '- LQ45: 45 saham paling likuid, kapitalisasi besar',
      '- IDX30: 30 saham dengan likuiditas tinggi',
      '- JII: Jakarta Islamic Index (sesuai syariah)',
      '- SRI-KEHATI: indeks saham ramah lingkungan',
      '',
      'STATISTIK INVESTOR (KSEI, 2025):',
      '- Total SID: 20,13 juta investor',
      '- Investor lokal: 99,78%',
      '- Investor Gen Z (di bawah 30 tahun): 52,59%',
      '- Pertumbuhan YoY: 35%',
      '',
      'JAM PERDAGANGAN:',
      '- Pra-pembukaan: 08:45-09:00 WIB',
      '- Sesi 1: 09:00-11:30 WIB',
      '- Sesi 2: 13:30-15:00 WIB',
      '',
      'INTEGRASI FinBest AI DENGAN BEI:',
      '- Real-time price data via IDX API atau broker partner (read-only)',
      '- RAG pipeline menggunakan data IDX terkini untuk rekomendasi berbasis fakta',
      '- MLOps otomatis memperbarui model setiap hari perdagangan',
    ]),
  },

  // ============ STOCK ANALYSIS ============
  {
    title: 'Analisis Fundamental Saham: Pendekatan Top-Down dan Bottom-Up',
    category: 'education',
    source: 'FinBest AI Knowledge Base',
    summary:
      'Analisis fundamental saham menggunakan pendekatan top-down (makro - industri - perusahaan) atau bottom-up (langsung ke perusahaan). Kombinasikan dengan rasio keuangan (PER, PBV, ROE, DER) untuk valuasi komprehensif.',
    content: buildContent([
      'ANALISIS FUNDAMENTAL SAHAM:',
      '',
      'PENDEKATAN TOP-DOWN:',
      '1. Analisis Makroekonomi: GDP, inflasi, suku bunga BI, nilai tukar IDR',
      '2. Analisis Industri: pertumbuhan sektor, kompetisi, regulasi, tren',
      '3. Analisis Perusahaan: posisi kompetitif, financials, manajemen',
      '',
      'PENDEKATAN BOTTOM-UP:',
      '- Langsung evaluasi perusahaan terlepas dari kondisi makro',
      '- Cocok untuk investor long-term yang percaya "perusahaan bagus tetap bagus"',
      '- Fokus pada quality (ROE tinggi, hutang rendah, growth konsisten)',
      '',
      'RASIO KEUANGAN KUNCI:',
      '',
      'VALUASI:',
      '- PER (Price Earning Ratio): Harga / EPS. PER < 10x undervalued, 10-20x wajar, > 30x premium',
      '- PBV (Price to Book Value): Harga / Nilai Buku. PBV < 1 value opportunity, 1-3 wajar, > 5 premium',
      '- EV/EBITDA: Enterprise Value / EBITDA (cocok untuk perusahaan dengan hutang besar)',
      '',
      'PROFITABILITAS:',
      '- ROE (Return on Equity): Laba / Ekuitas. ROE > 15% baik, > 20% sangat baik',
      '- ROA (Return on Assets): Laba / Total Aset',
      '- Net Profit Margin: Laba Bersih / Pendapatan',
      '',
      'KESEHATAN KEUANGAN:',
      '- DER (Debt to Equity): Hutang / Ekuitas. < 1 sehat, 1-2 moderat, > 3 berisiko',
      '- Current Ratio: Aset Lancar / Hutang Lancar (> 1.5 sehat)',
      '- Interest Coverage Ratio: EBIT / Beban Bunga (> 3 aman)',
      '',
      'PERTUMBUHAN:',
      '- Revenue Growth YoY: pertumbuhan pendapatan tahunan',
      '- Earnings Growth YoY: pertumbuhan laba tahunan',
      '- CAGR 5 tahun: Compound Annual Growth Rate',
      '',
      'KUALITAS PERUSAHAAN:',
      '- Economic Moat: brand, network effect, cost advantage',
      '- Kepemilikan institusional: % saham dimiliki reksa dana/asuransi',
      '- Insider ownership: % saham dimiliki manajemen (alignment)',
      '',
      'CONTOH ANALISIS BBCA:',
      '- PER: 6.8x (di bawah rata-rata perbankan 7.5x)',
      '- PBV: 2.1x (premium untuk kualitas)',
      '- ROE: 24% (sangat tinggi, konsisten)',
      '- NPL: 1.9% (rendah, terkendali)',
      '- CAR: 23% (jauh di atas minimum 8%)',
      '',
      'CATATAN: Analisis fundamental bukan jaminan return. Kombinasikan dengan analisis teknikal untuk timing, dan sesuaikan dengan profil risiko pribadi.',
    ]),
  },
  {
    title: 'Analisis Teknikal Saham: Trend, Support, Resistance, dan Volume',
    category: 'education',
    source: 'FinBest AI Knowledge Base',
    summary:
      'Analisis teknikal membaca pergerakan harga dan volume untuk mengidentifikasi pola dan tren. Konsep utama: support, resistance, trendline, moving average, RSI, MACD.',
    content: buildContent([
      'ANALISIS TEKNIKAL SAHAM:',
      '',
      'PRINSIP DASAR:',
      '1. Harga diskon semua informasi (semua news sudah tercermin di harga)',
      '2. Pergerakan harga membentuk tren (uptrend, downtrend, sideways)',
      '3. History repeats itself (pola berulang karena psikologi pasar)',
      '',
      'KONSEP UTAMA:',
      '',
      '1. TREND: Uptrend (higher highs + higher lows), Downtrend (lower highs + lower lows), Sideways',
      '2. SUPPORT: level harga di mana tekanan beli > jual (harga cenderung bounce)',
      '3. RESISTANCE: level harga di mana tekanan jual > beli (harga cenderung ditolak)',
      '4. BREAKOUT: harga menembus resistance (bullish) atau support (bearish)',
      '',
      'INDIKATOR POPULER:',
      '',
      '1. MOVING AVERAGE (MA): SMA 50 (tren menengah), SMA 200 (tren panjang). Golden cross: SMA50 menembus SMA200 ke atas.',
      '2. RSI (Relative Strength Index): 0-100. RSI > 70 overbought, < 30 oversold. Divergence = sinyal reversal.',
      '3. MACD: MACD line (12 EMA - 26 EMA), Signal line (9 EMA dari MACD). Buy: MACD menembus signal ke atas.',
      '4. BOLLINGER BANDS: MA20 +/- 2 std dev. Harga sentuh upper = overbought, lower = oversold.',
      '',
      'POLA CHART:',
      '- Double Top: pola bearish reversal (2 puncak)',
      '- Double Bottom: pola bullish reversal (2 lembah)',
      '- Head and Shoulders: pola bearish reversal (3 puncak, tengah tertinggi)',
      '- Triangle: continuation pattern',
      '',
      'KETERBATASAN:',
      '- Tidak 100% akurat (berbasis probabilitas)',
      '- Saham kecil/illiquid: pola tidak reliable',
      '- Market manipulation: "gorengan" dapat menyesatkan',
      '- False signal: butuh konfirmasi multiple indikator',
      '',
      'STRATEGI KOMBINASI:',
      '- Fundamental untuk memilih saham (apa yang beli)',
      '- Teknikal untuk timing (kapan beli/jual)',
      '- Risk management untuk proteksi (stop-loss, position sizing)',
      '',
      'FinBest AI menyediakan analisis teknikal sebagai konteks tambahan, bukan rekomendasi transaksi.',
    ]),
  },

  // ============ REGULASI TAMBAHAN ============
  {
    title: 'POJK Tata Kelola Teknologi Informasi Sektor Jasa Keuangan',
    category: 'regulations',
    source: 'POJK Nomor 11/POJK.03/2022',
    summary:
      'Regulasi OJK tentang tata kelola teknologi informasi untuk lembaga jasa keuangan, termasuk aplikasi fintech. Mencakup manajemen risiko IT, keamanan data, dan kepatuhan cloud.',
    content: buildContent([
      'TATA KELOLA TEKNOLOGI INFORMASI SEKTOR JASA KEUANGAN:',
      '',
      'DASAR HUKUM: POJK Nomor 11/POJK.03/2022 tentang Penyelenggaraan Teknologi Informasi oleh Lembaga Jasa Keuangan',
      '',
      'RUANG LINGKUP: Bank, sekuritas, asuransi, dana pensiun, fintech, P2P lending.',
      '',
      'PRINSIP TATA KELOLA IT:',
      '1. Komite Tata Kelola IT - Dewan Komisaris harus membentuk Komite IT',
      '2. Manajemen Risiko IT - identifikasi, mitigasi, penilaian risiko tahunan',
      '3. Keamanan Data - enkripsi AES-256 at-rest, TLS 1.3 in-transit, RBAC, MFA',
      '4. Pengelolaan Cloud - data residency Indonesia, SLA 99.5%, exit strategy',
      '5. Aplikasi Mobile - secure coding (OWASP), penetration testing tahunan',
      '6. API dan Integrasi - OAuth 2.0, rate limiting, input validation',
      '',
      'KEPATUHAN FINBEST AI:',
      '- Infrastruktur cloud dengan data center di Indonesia',
      '- Enkripsi AES-256 at-rest, TLS 1.3 in-transit',
      '- Audit trail semua akses data pengguna',
      '- Penetration testing kuartalan oleh pihak ketiga',
      '- OJK Regulatory Sandbox 12 bulan untuk validasi',
      '',
      'HAK PENGGUNA SESUATU REGULASI:',
      '1. Persetujuan eksplisit sebelum pengolahan data',
      '2. Hak akses dan ekspor data (format JSON/CSV)',
      '3. Hak penghapusan akun dan data terkait',
      '4. Notifikasi pelanggaran data dalam 3x24 jam',
      '5. Audit log tersedia untuk inspeksi pengguna',
      '',
      'SANKSI PELANGGARAN: peringatan tertulis, denda hingga Rp 15 miliar, pembatasan kegiatan, pencabutan izin.',
    ]),
  },
  {
    title: 'Regulasi OJK tentang Edukasi Investor dan Wajib Paham',
    category: 'regulations',
    source: 'SOJK Nomor 20/SEOJK.04/2018',
    summary:
      'OJK mewajibkan edukasi investor melalui program Wajib Paham. Investor wajib mengikuti kuesioner profil risiko dan edukasi sebelum berinvestasi. FinBest AI menyelaraskan modul edukasi dengan regulasi ini.',
    content: buildContent([
      'PROGRAM WAJIB PAHAM OJK:',
      '',
      'DASAR HUKUM: SOJK Nomor 20/SEOJK.04/2018 tentang Program Wajib Paham dan Edukasi Investor',
      '',
      'TUJUAN PROGRAM:',
      '- Meningkatkan literasi keuangan masyarakat',
      '- Melindungi investor dari produk tidak sesuai profil risiko',
      '- Mendorong keputusan investasi rasional',
      '',
      'KEWAJIBAN PENYEDIA LAYANAN INVESTASI:',
      '1. Memberikan edukasi minimal sebelum investor membuka akun',
      '2. Kuesioner profil risiko wajib diisi sebelum transaksi pertama',
      '3. Re-assessment profil risiko minimal 1 tahun sekali',
      '4. Materi edukasi: risiko, jenis produk, mekanisme pasar',
      '5. Disclaimer dalam bahasa Indonesia yang jelas',
      '',
      'HAK INVESTOR:',
      '1. Mendapatkan edukasi yang memadai sebelum investasi',
      '2. Memilih produk sesuai profil risiko',
      '3. Akses informasi lengkap tentang produk',
      '4. Mekanisme komplain ke OJK jika dilanggar',
      '',
      'PROFIL RISIKO OJK (5 KATEGORI):',
      '1. KONSERVATIF: maks saham 10%, fokus deposito & SBN',
      '2. MODERAT KONSERVATIF: maks saham 25%, obligasi dominan',
      '3. MODERAT: saham 30-50%, keseimbangan saham-obligasi',
      '4. MODERAT AGRESIF: saham 50-70%, fokus pertumbuhan',
      '5. AGRESIF: saham 70-90%, toleransi volatilitas tinggi',
      '',
      'FinBest AI mengimplementasikan:',
      '- Kuesioner 10 pertanyaan sesuai standar OJK',
      '- Edukasi personal sesuai profil risiko',
      '- Re-assessment otomatis tahunan',
      '- Disclaimer dalam Bahasa Indonesia di setiap rekomendasi AI',
    ]),
  },

  // ============ COGNITIVE BIAS DETECTION GUIDE (for AI) ============
  {
    title: 'Panduan Deteksi Bias untuk Asisten AI: Sinyal dan Intervensi',
    category: 'education',
    source: 'FinBest AI - Internal Bias Detection Guide',
    summary:
      'Panduan internal untuk AI FinBest dalam mendeteksi sinyal bias kognitif dari pertanyaan dan pola perilaku pengguna. Sertakan intervensi edukatif yang tepat.',
    content: buildContent([
      'PANDETIAN BIAS KOGNITIF OLEH AI FINBEST:',
      '',
      '1. DETEKSI FOMO',
      'Sinyal dari pertanyaan pengguna:',
      '- "Saham X naik gila-gilaan, harus beli ga sih?"',
      '- "Teman saya udah untung 50% dari saham Y, saya kebagian ga?"',
      '- "Berita viral saham Z mau naik, buruan beli?"',
      '',
      'Intervensi AI:',
      '- Validasi perasaan: "Saya mengerti kekhawatiran Anda ketinggalan peluang."',
      '- Edukasi: "Kenaikan harga belum tentu berlanjut. Mari kita analisis fundamentalnya."',
      '- Tanyakan: "Apa yang membuat Anda tertarik, selain kenaikan harganya?"',
      '- Kontekstualisasi: "Historis, saham yang naik >15% dalam 5 hari rata-rata koreksi 8% dalam 2 minggu."',
      '',
      '2. DETEKSI HERDING',
      'Sinyal:',
      '- "Semua orang bilang saham X bakal naik"',
      '- "Group WhatsApp saya rekomendasi beli Y"',
      '- "Influencer @z bilang Z akan dibanting harga"',
      '',
      'Intervensi:',
      '- "Rekomendasi dari grup/influenser perlu diverifikasi dengan data. Mari kita cek fundamentalnya."',
      '- "Herd behavior sering menyebabkan bubble. Pertimbangkan thesis investasi mandiri."',
      '- Sediakan data fundamental vs hype',
      '',
      '3. DETEKSI OVERCONFIDENCE',
      'Sinyal:',
      '- "Saya yakin saham X bakal naik 100% bulan depan"',
      '- "Saya sudah jago trading, ga perlu analisis fundamental"',
      '- "Saya bisa timing market, beli di bawah jual di atas"',
      '',
      'Intervensi:',
      '- "Prediksi pasti dalam investasi sangat sulit. Mari kita evaluasi dengan data historis."',
      '- "95% trader aktif kalah dari indeks dalam jangka panjang. Pertimbangkan strategi DCA."',
      '- Dorong diversifikasi: "Konsentrasi pada 1-2 saham meningkatkan risiko. Bagaimana alokasi Anda?"',
      '',
      '4. DETEKSI LOSS AVERSION',
      'Sinyal:',
      '- "Saham saya udah rugi 40%, saya tahan aja ya, nanti balik"',
      '- "Ga mau cut loss, sayang dana yang udah masuk"',
      '- "Mending averaging down daripada realisasi rugi"',
      '',
      'Intervensi:',
      '- "Loss aversion adalah bias natural, tapi evaluasi berdasarkan prospek masa depan, bukan harga beli."',
      '- "Tanyakan: Jika Anda belum punya saham ini, apakah akan beli sekarang?"',
      '- "Cut loss adalah realokasi modal ke investasi yang lebih menjanjikan, bukan kekalahan."',
      '',
      '5. DETEKSI ANCHORING',
      'Sinyal:',
      '- "Saham ini dulu Rp 10.000, sekarang Rp 5.000, pasti balik ke 10.000"',
      '- "Harga all-time high-nya Rp 20.000, saya tunggu sampe situ"',
      '',
      'Intervensi:',
      '- "Harga historis bukan prediktor masa depan. Mari evaluasi fundamental terkini."',
      '- "Bandingkan dengan valuasi sektor dan prospek pertumbuhan, bukan harga masa lalu."',
      '',
      'PRINSIP INTERVENSI AI FINBEST:',
      '1. Tidak menghakimi - validasi emosi pengguna',
      '2. Berbasis data - gunakan statistik dan rasio keuangan',
      '3. Edukatif - jelaskan konsep, bukan hanya saran',
      '4. Non-diskrisioner - keputusan tetap di tangan pengguna',
      '5. Sertakan disclaimer bahwa saran bersifat edukatif',
    ]),
  },
]

async function main() {
  console.log('Seeding additional knowledge base...')

  for (const doc of additionalDocs) {
    const existing = await prisma.knowledgeDocument.findFirst({
      where: { title: doc.title },
    })
    if (existing) {
      console.log('  Skip (exists): ' + doc.title.slice(0, 50) + '...')
      continue
    }
    await prisma.knowledgeDocument.create({ data: doc })
    console.log('  Added: ' + doc.title.slice(0, 50) + '...')
  }

  const total = await prisma.knowledgeDocument.count()
  console.log('Total knowledge documents: ' + total)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
